### ISSUE TITLE
miss Stats2.pm module

### ISSUE THREAD

**Issue by chenwenyan2015** [charlesbreeze/FORGE2#3]
Hi, thanks for your great tools!
I have a question. When I run the command `eforge.pl -f file -label myte`, an error occurs "Can't locate Forge2/Stats2.pm in @INC (you may need to install the Forge2::Stats2 module)"
Can you tell me how to find the module "Stats2.pm"?
Thanks very well!

**Comment by charlesbreeze** [comment]
I have added Forge2/Stats2.pm in /bin, let me know if this works on your side

**Comment by chenwenyan2015** [comment]
Great! It works now. Thanks!
